### ISSUE TITLE
requirements to run all the containers

### ISSUE THREAD

**Issue by kript** [irods/irods_demo#13]
Apologies if I've missed this somewhere, but if I wanted to spin up an AWS instance (other cloud providers are available), what quantity of RAM and number of cores would I need?

Thanks for this resource!

**Comment by trel** [comment]
A fine question.

I just cloned and ran `docker-compose up` on a `t2.medium` EC2 instance with:
 - 2 vCPU
 - 4 GB RAM
 - 20 GB storage

This virtual machine is enough, but probably only for a demo - not for any real load.

**Comment by trel** [comment]
After initial launch, there were 7.5GB used, so I have marked 10GB as a minimum requirement.

**Comment by trel** [comment]
Tried to go smaller... it did not work.

`t2.small` with 1 vCPU and 2 GB RAM was not enough for all the containers to stand up.
