### ISSUE TITLE
Elk Stack Demo dashboard instructions

### ISSUE THREAD

**Issue by kript** [irods/irods_demo#14]
Hi folks,

I remember from the course one had to do something extra to get the demo dashboard to show data, but at the moment all I can get it to do is report 'could not create the vizualisation'; I suspect I have not created the correct index, or data is not reaching the elastic instance, can the instructions be updated with the additional step required please?

**Comment by alanking** [comment]
Have you have tried following the steps in the training? http://slides.com/irods/ugm2019-administration-getting-started#/9

The instructions are a bit... brief, yes. I'll mark this as a Documentation issue.

I just tried this out on my local setup using the training steps and it seems to work fine.

**Comment by kript** [comment]
It certinaly created an index pattern called `irods_index` but the dashboard window shows this;
![image](https://user-images.githubusercontent.com/958908/102100328-393bdf00-3e21-11eb-8cc1-50362ff81d69.png)

followed by this;

![image](https://user-images.githubusercontent.com/958908/102100410-4e187280-3e21-11eb-8d33-3720a2513c1b.png)

(incidentally, I was _this_ many years old when I discovered you can copy and pase screencaps into github!)

**Comment by kript** [comment]
ah, as of 980b83ba1f2c3ea2bbeecb9ae1d5efeb3c3cd169 this appears to be working for me now, thank you.
