### ISSUE TITLE
Connection timed out connecting to nfsrods from outside network

### ISSUE THREAD

**Issue by rudibroekhuizen** [irods/irods_demo#28]
I try to mount a nfsrods volume on my laptop. 

Command `sudo mount -o sec=sys,port=2049 publicipaddressofthedockerhost:/ /mnt/nfsrods` results in this error message: mount.nfs: `Connection timed out.`

**Comment by trel** [comment]
This should behave - has been demonstrated to work.

Please update if you have any new information.

**Comment by alanking** [comment]
I'll make sure to take care of this once NFSRODS is added.

**Comment by alanking** [comment]
Please try out the new NFSRODS service and see if things behave any differently.

**Comment by trel** [comment]
closing - this is working for us.
