### ISSUE TITLE
Using NFS client in iRODS demo

### ISSUE THREAD

**Issue by scaleoutsean** [irods/irods_demo#44]
> Once the service is running, the NFS server needs to be accessed from a mountpoint.

Does this apply only to nfs4j?

Is it possible to mount a generic NFSv4 share from Provider container, and use it similarly to local POSIX filesystem path? Assuming Linux NFSv4 client is installed and used for that.

**Comment by trel** [comment]
> Does this apply only to nfs4j?

That's just an implementation detail - so... no?

> Is it possible to mount a generic NFSv4 share from Provider container, and use it similarly to local POSIX filesystem path?

I think the answer to your question is yes.   You should be able to mount the NFS service from anywhere that can 'see' it, and then you should be able to treat it as a local POSIX filesystem (the promise/goal of NFS).  Edits made within that mountpoint should appear in the iRODS namespace, triggering any/all relevant policy.

**Comment by alanking** [comment]
You may have to enable enable additional permissions on the container in order to use mount points, unless you're referring to adding a mounted volume via Docker.

**Comment by scaleoutsean** [comment]
Thanks for the answers. To Alan's point, that's not straightfoward, but I from nfs4j docs I understood it's NFS-to-iRODS gateway which "virtualizes" iRODS resources behind it, while I plan to use NFS mount as another local POSIX filesytem (and use i commands when I treat it as local FS). Good point about mounting NFS from Docker (permissions, etc.).

**Comment by trel** [comment]
You would not use iCommands inside the mount point - just regular unix/POSIX commands at that point.

The NFSRODS layer is doing the translation from system calls to the iRODS protocol.

**Comment by trel** [comment]
I think there is nothing actionable here - closing.   If a problem is found, please open a new issue.
