### ISSUE TITLE
Build fails due to missing dependency

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_demo#46]
I noticed that rirods GitHub workflows, that rely on the irods demo, started failing. https://github.com/irods/irods_client_library_rirods/actions/runs/6607881022/job/17945814952

**Comment by trel** [comment]
nothing has moved here - could be an assumed 'latest' version that is now incorrect since we just released iRODS 4.3.1...

**Comment by trel** [comment]
I think what we're finding is that `4.3.0-1~focal` does not appear to all tooling as `4.3.0`, as the 'Provides' suggests.

```
Provides: irods-runtime (= 4.3.0)
```

**Comment by alanking** [comment]
@trel - Please close if complete
