### ISSUE TITLE
Error trying to docker-compose up in Windows

### ISSUE THREAD

**Issue by kuhlaid** [irods/irods_demo#8]
Well the process made it to 'Get:132' then threw this error:
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.1-6_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'irods-automated-ingest' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y sudo wget lsb-release apt-transport-https python-pip redis-server curl' returned a non-zero code: 100
```

**Comment by trel** [comment]
hm... works here.    try again?    network hiccup?

**Comment by kuhlaid** [comment]
I executed the command again and it seemed to get most of the containers loaded but then ran into this in Docker:
```
icat.example.org on 127.0.0.11:53: no such host. Sleeping 1s

irods-client_1 | 2020/05/19 23:28:26 Problem with dial: dial tcp: lookup icat.example.org on 127.0.0.11:53: no such host. Sleeping 1s

irods-nfsrods_1 | 2020/05/19 23:28:27 Problem with dial: dial tcp: lookup icat.example.org on 127.0.0.11:53: no such host. Sleeping 1s

irods-davrods_1 | 2020/05/19 23:28:27 Problem with dial: dial tcp: lookup icat.example.org on 127.0.0.11:53: no such host. Sleeping 1s
```

**Comment by trel** [comment]
a quick googling suggests it could be related to proxy settings?

https://stackoverflow.com/questions/54559335/dial-tcp-lookup-no-such-host-issue-on-docker-windows-desktop

https://stackoverflow.com/questions/33893150/dial-tcp-lookup-xxx-xxx-xxx-xxx-no-such-host/53848018

**Comment by kuhlaid** [comment]
I changed my Docker Proxy/DNS settings to use manual DNS configuration (8.8.8.8) but two of the containers are not loading:
![image](https://user-images.githubusercontent.com/41551429/82391943-a9f85580-9a10-11ea-8891-38b920c720f0.png)

**Comment by kuhlaid** [comment]
It finally timed out with:
![image](https://user-images.githubusercontent.com/41551429/82392095-fe033a00-9a10-11ea-9437-a841fa6011b0.png)

**Comment by trel** [comment]
You're looking to find the reason for  `irods_demo_irods-catalog-provider_1 exited (1)`.

The others were waiting for it, and it never stood up.

**Comment by kuhlaid** [comment]
The Docker logs are not helpful. I can't tell if there is a problem with icat.example.org or if iRODS is trying to pull something from that server that it can't reach.

**Comment by trel** [comment]
iRODS is trying to stand up in a docker container called icat.example.org - that's not a real hostname on the internet.

Something is going sideways when iRODS is being installed/configured/launched.

**Comment by kuhlaid** [comment]
Are you able to get this to spin up on a Windows machine?

**Comment by trel** [comment]
No, not at this time - but primarily because I don't have access to a Windows machine.

**Comment by kuhlaid** [comment]
Okay, I am trying to get it running on OpenShift instead and see how that goes.

**Comment by alanking** [comment]
I was able to resolve this by making the following change in ingest/Dockerfile:
```
diff --git a/ingest/Dockerfile b/ingest/Dockerfile
index 6b66e3e..f678b28 100644
--- a/ingest/Dockerfile
+++ b/ingest/Dockerfile
@@ -4,7 +4,8 @@
 FROM ubuntu:16.04

 # Install automated ingest and redis-server
-RUN apt-get update && \
+RUN DEBIAN_FRONTEND=noninteractive && \
+    apt-get update && \
     apt-get install -y sudo wget lsb-release apt-transport-https python-pip redis-server curl

 # Install icommands to create environment file
```
Please give that a try and let us know if it works.

I also had to temporarily disable davrods because the recent 4.2.8 release is not yet supported. The demo stood up successfully after that. HOWEVER, my laptop (the Windows machine on which this was tested) is crying bitter tears under the weight of the demo, so I would advise only running this on a beefy machine.

Thanks!

**Comment by kuhlaid** [comment]
@alanking Does that mean I need to run the 'docker-compose up' command from within the ingest folder for Windows?

**Comment by kuhlaid** [comment]
Related to Docker, can iRods be propped up without root user in cloud containers? I tried adding `USER 1001` to my Docker file that I sent to OpenShift cloud to try and build an image, but that failed.

**Comment by alanking** [comment]
No, you would run `docker-compose up` (or `docker-compose build` if you just want to build) in the location of the .yml file. Simply apply the change to the ingest/Dockerfile file and the docker-compose.yml in the root directory of the project is pointed at that file. I have issued a pull request to fix this.

As for the second question, I'm not entirely sure what you're trying to do but I do know that there are some things that require privileged access (such as installation of system packages, starting services, setting up the database, etc.). This demo environment will probably always require this.

**Comment by kuhlaid** [comment]
Thanks @alanking. Back to the Windows Docker compose, I pulled the latest code, trashed the last container I tried to build, then ran `docker-compose up` with the same problems as shown here:
![image](https://user-images.githubusercontent.com/41551429/83302266-0144b580-a1c9-11ea-81ae-1d83fbe28f1e.png)

**Comment by kuhlaid** [comment]
Dang it, I tried rebuilding the iRods images and Docker throws this error:
```
The following packages have unmet dependencies:
 davrods : Depends: irods-runtime (= 4.2.7) but 4.2.8 is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'irods-davrods' failed to build: The command 
'/bin/sh -c wget -O /davrods.deb 
https://github.com/UtrechtUniversity/davrods/releases/download/4.2.7_1.4.2/davrods-4.2.7-1.4.2.deb
 && apt install -y /davrods.deb' returned a non-zero code: 100
```

**Comment by trel** [comment]
> I also had to temporarily disable davrods because the recent 4.2.8 release is not yet supported.

yes, please comment davrods out for now - it's not yet released for 4.2.8.

https://github.com/irods/irods_demo/blob/cf704767ef7ceae73ec366f2814f2d9a5bf93ab2/docker-compose.yml#L104-L114

**Comment by kuhlaid** [comment]
@trel Thanks. After the commenting out davrods in the docker-compose.yml and changing the .sh files to have UNIX end of line characters I am no longer seeing the `standard_init_linux.go:211` error during the image builds. 

The `Problem with dial: dial tcp 172.21.0.4:1247: connect: connection refused` comments kept scrolling through my terminal for a while and all of the Docker images appeared to be running at one point. This is my full terminal output:

[iRodsDockerComposeTerminalOutput.txt](https://github.com/irods/irods_demo/files/4704737/iRodsDockerComposeTerminalOutput.txt)

**Comment by trel** [comment]
Looks like iRODS was on its way, and eventually finished, but took too long for the others who were waiting for it to be 'available' (4min10s).  

The four containers that timed-out... all have `-timeout 250s` in their Dockerfiles...

```
irods-client_1            | 2020/05/29 23:04:44 Timeout after 4m10s waiting on dependencies to become available: [tcp://icat.example.org:1247]
irods-metalnx_1           | 2020/05/29 23:04:52 Timeout after 4m10s waiting on dependencies to become available: [tcp://icat.example.org:1247 tcp://irods-metalnx-db.example.org:5432]
irods-automated-ingest_1  | 2020/05/29 23:04:56 Timeout after 4m10s waiting on dependencies to become available: [tcp://icat.example.org:1247]
irods-nfsrods_1           | 2020/05/29 23:04:56 Timeout after 4m10s waiting on dependencies to become available: [tcp://icat.example.org:1247]
```

Just bump those values up to give your computer time to get everything up, and I believe you'll be in business.

https://github.com/irods/irods_demo/blob/cf704767ef7ceae73ec366f2814f2d9a5bf93ab2/irods-client/Dockerfile#L16
https://github.com/irods/irods_demo/blob/cf704767ef7ceae73ec366f2814f2d9a5bf93ab2/metalnx/Dockerfile#L19
https://github.com/irods/irods_demo/blob/cf704767ef7ceae73ec366f2814f2d9a5bf93ab2/ingest/Dockerfile#L36
https://github.com/irods/irods_demo/blob/cf704767ef7ceae73ec366f2814f2d9a5bf93ab2/nfsrods/Dockerfile#L28

**Comment by kuhlaid** [comment]
Thanks @trel. I bumped up the timeouts to 500s. Do you think it needs more time? This is what happened this round:

[iRodsDockerComposeTerminalOutput.txt](https://github.com/irods/irods_demo/files/4704846/iRodsDockerComposeTerminalOutput.txt)

**Comment by trel** [comment]
you need to start cleanly.

```
irods-catalog-provider_1  | +-----------------------------------------------------+
irods-catalog-provider_1  | | WARNING:                                            |
irods-catalog-provider_1  | | The database specified is an already-configured     |
irods-catalog-provider_1  | | iRODS database, so first-time database setup will   |
irods-catalog-provider_1  | | not be performed. Providing different inputs from   |
irods-catalog-provider_1  | | those provided the first time this script was run   |
irods-catalog-provider_1  | | will result in unspecified behavior, and may put    |
irods-catalog-provider_1  | | a previously working zone in a broken state. It's   |
irods-catalog-provider_1  | | recommended that you exit this script now if you    |
irods-catalog-provider_1  | | are running it manually. If you wish to wipe out    |
irods-catalog-provider_1  | | your current iRODS installation and associated data |
irods-catalog-provider_1  | | catalog, drop the database and recreate it before   |
irods-catalog-provider_1  | | re-running this script.                             |
irods-catalog-provider_1  | +-----------------------------------------------------+
```

**Comment by kuhlaid** [comment]
I started cleanly after bumping up the timeouts. It took about 18 minutes to prop everything up once all of the images were built. These were the latest messages.
[iRodsDockerComposeTerminalOutput.txt](https://github.com/irods/irods_demo/files/4712382/iRodsDockerComposeTerminalOutput.txt)

The VM brought my system to a crawl because it was writing so much to disk, so I would need to load this demo into a cloud container to have something workable. Thanks.

**Comment by alanking** [comment]
Just making a note here... Perhaps an improvement to this in the future would be to make it easier to switch on/off different parts of the demo in order to make it useable on smaller machines.

**Comment by trel** [comment]
Is there a way to do that?   some conditional logic based on a config file?

**Comment by alanking** [comment]
`docker-compose up` allows you list services that you want to run (a whitelist, if you will). 

```
Usage: up [options] [--scale SERVICE=NUM...] [SERVICE...] 
```

So maybe we could make a wrapper script which allows selectively filtering services and performs the appropriate `docker-compose` command (the catalog provider and ICAT are the minimum viable demo). Maybe something like...

```
$ ./run_irods_demo.sh [--exclude SERVICE...] [--include SERVICE...]
```

Or we could slice different services into different logical groupings (e.g. `--client <metalnx | davrods | icommands>`). Just a couple of ideas.

**Comment by trel** [comment]
okay, yeah, let's start with just updating the README with a couple of minimal examples of how to hold it to get a cross-section of functionality.  Can discuss offline.
